language: node_js
sudo: true
node_js:
- '7'
- '6'
- '5'
- '4'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
- npm install
- npm run build
script:
- npm run lint
- npm run test
- npm run karma-travis