language: node_js
sudo: true
node_js:
- '7'
- '6'
- '5'
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
install:
- npm install
- npm run build
script:
- npm run lint
- npm run test
- npm run karma-travis